# SPDX-FileCopyrightText: 2020 Tocqueville Group
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

name:                tasty-hunit-compat
version:             0.2
github:              serokell/tasty-hunit-compat
category:            Testing
synopsis:            Tasty integration with the existing HUnit package.
description:         Existing `tasty-hunit` package now declares its own testing primitives.
                     This package provides an integration of the existing HUnit package with Tasty that inter-operates properly with other HUnit code.
author:              Serokell, Tocqueville Group
maintainer:          Serokell <hi@serokell.io>
copyright:           2020 Tocqueville Group
license:             MPL-2.0
license-file:        LICENSE

extra-source-files:
  - README.md
  - CHANGELOG.md

library:
  source-dirs: src

  dependencies:
    - base >= 4.7 && < 5
    - HUnit
    - tasty
    - tasty-hunit
